package request

import (
	"encoding/json"
	"errors"
	"fmt"
	loggerAware "gitlab.altex.ro/plug/go_atx_lib/logger"
	logger "gitlab.altex.ro/plug/go_logger"
	"io"
	"net/http"
	"strings"
)

type RequestError struct {
	statusCode int
	errorMsg   string
}

func NewRequestError(statusCode int, errorMsg string) *RequestError {
	return &RequestError{errorMsg: errorMsg, statusCode: statusCode}
}

func (n RequestError) Error() string {
	return n.errorMsg
}

func (n RequestError) GetStatus() int {
	return n.statusCode
}

type RequestErrorHandler struct {
	loggerAware.LoggerAware
}

/**
 * @desc construct
 *
 * @return RequestErrorHandler
 */
func NewNormalizerErrorHandler(logger logger.Logger) *RequestErrorHandler {
	neh := &RequestErrorHandler{}
	neh.SetLogger(logger)

	return neh
}

/**
 * @desc maps an error{} to a  RequestError{} so we can have an ubiquitous error type
 *
 * @param err error - an error generated by a normalizer
 * @return RequestError
 */
func (n RequestErrorHandler) HandleError(err error) *RequestError {
	var normalizerErr *RequestError
	if errors.As(err, &normalizerErr) {
		return normalizerErr
	}

	n.GetLogger().Error("[RequestErrorHandler]: " + err.Error())
	return &RequestError{
		statusCode: http.StatusInternalServerError,
		errorMsg:   http.StatusText(http.StatusInternalServerError),
	}
}

type RequestNormalizer struct{}

/**
 * @desc maps the request into a given struct
 *
 * @param r io.Reader - source to read from
 * @param dest interface{} - pointer to map the request payload
 * @return error|nil
 */
func (n RequestNormalizer) Normalize(r io.Reader, dest interface{}) error {
	decoder := json.NewDecoder(r)
	decoder.DisallowUnknownFields()

	err := decoder.Decode(&dest)
	if err != nil {

		var syntaxError *json.SyntaxError
		var unmarshalTypeError *json.UnmarshalTypeError

		switch {
		case errors.As(err, &syntaxError):
			msg := fmt.Sprintf("Request body contains badly-formed JSON (at position %d)", syntaxError.Offset)
			return &RequestError{statusCode: http.StatusBadRequest, errorMsg: msg}

		case errors.Is(err, io.ErrUnexpectedEOF):
			msg := fmt.Sprintf("Request body contains badly-formed JSON")
			return &RequestError{statusCode: http.StatusBadRequest, errorMsg: msg}

		case errors.As(err, &unmarshalTypeError):
			msg := fmt.Sprintf("Request body contains an invalid value for the %q field (at position %d)", unmarshalTypeError.Field, unmarshalTypeError.Offset)
			return &RequestError{statusCode: http.StatusBadRequest, errorMsg: msg}

		case strings.HasPrefix(err.Error(), "json: unknown field "):
			fieldName := strings.TrimPrefix(err.Error(), "json: unknown field ")
			msg := fmt.Sprintf("Request body contains unknown field %s", fieldName)
			return &RequestError{statusCode: http.StatusBadRequest, errorMsg: msg}

		case errors.Is(err, io.EOF):
			msg := "Request body must not be empty"
			return &RequestError{statusCode: http.StatusBadRequest, errorMsg: msg}

		case err.Error() == "http: request body too large":
			msg := "Request body must not be larger than 1MB"
			return &RequestError{statusCode: http.StatusRequestEntityTooLarge, errorMsg: msg}

		default:
			return err
		}
	}

	err = decoder.Decode(&struct{}{})
	if err != io.EOF {
		msg := "Request body must only contain a single JSON object"
		return &RequestError{statusCode: http.StatusBadRequest, errorMsg: msg}
	}

	return nil
}
